### ISSUE TITLE
pkg apply-hot-fix mangles a file URL for a p5p archive

### ISSUE THREAD

**Issue by v-a-b** [omniosorg/pkg5#242] opened 2020-08-29 17:25 UTC
When applying a hotfix from a local archive, pkg will first display the path correctly:

# pkg apply-hot-fix -nv --be-name=amd-hma-exclusion amd-hma-exclusion.p5p
Resolved URL to: file:///tmp/amd-hma-exclusion.p5p
Retrieving installed package list...
Scanning package archive...
    pkg://omnios/system/kernel/platform@0.5.11-151034.0:20200828T150837Z will be updated.
...

and then fail, because it broke the URL:

The origin URIs for 'omnios' do not appear to point to a valid pkg repository.
...
# pkg publisher
PUBLISHER                   TYPE     STATUS P LOCATION
omnios                      origin   online F file:///tmp/pkg_hfa__o5dv8t4_amd-hma-exclusion.p5p/
omnios                      origin   online F http://pkg.bb-c.de/omnios/034-core/

It will also leave the broken origin in all NGZs that it wants to recurse into.

**Comment by citrus-it** [comment] 2020-08-29 18:36
Duplicate of https://github.com/omniosorg/pkg5/issues/184

**Closed by citrus-it** 2020-08-29 18:36 UTC
